#
#  Copyright (c) 2007 by Spirent Communications Inc.
#  All Rights Reserved.
#
#  This software is confidential and proprietary to Spirent Communications Inc.
#  No part of this software may be reproduced, transmitted, disclosed or used
#  in violation of the Software License Agreement without the expressed
#  written consent of Spirent Communications Inc.
#
# $Id: //TestCenter/p2.30_dev_ifmgr/content/traffic/l2l3/il/Generator/Learning/SConscript#1 $
#

import os

Import('*')

sources = [
    'EngineHooks.cpp',
    'FlowEngine.cpp',
    'FlowInstance.cpp',
    'PacketFactory.cpp',
    'PktLoopHandler.cpp',
    'AttackInstance.cpp',
    'StreamInstance.cpp',
    'PlaylistEngine.cpp',
    'FlowLoopHandler.cpp',
    'StreamLoopHandler.cpp',
    'AttackLoopHandler.cpp',
    'PlaylistInstance.cpp',
    'AttackPlaylistInstance.cpp',
    'StreamPlaylistInstance.cpp',
    'ModifierBlock.cpp',
    'Uint128.cpp'
    ]

e = env.Clone()

e['CPPPATH'] += [ '.',
                  '#content/traffic/l4l7/il',
                  '#framework/common/lib', 
                  '#framework/il/common/lib', 
                  ]

e['LIBS'] += [ 'ACE',
               'phxexception',
               'phxerrno',
               'bllutils',
               ]

libname = 'l4l7engine'

lib = e.SharedLibrary(target=conf['lib_dir']+'/'+libname, source=sources)
utils.installSharedLib(e, lib)

if env['utest'] :
    utest = SConscript(os.path.join('utest', 'SConscript'))
    utils.coverageReport(e, utest)

# Local Variables:
# mode:python
# End:
# vim: syntax=python
