#
#  Copyright (c) 2006 by Spirent Communications Inc.
#  All Rights Reserved.
#
#  This software is confidential and proprietary to Spirent Communications Inc.
#  No part of this software may be reproduced, transmitted, disclosed or used
#  in violation of the Software License Agreement without the expressed
#  written consent of Spirent Communications Inc.
#
# $Id: //TestCenter/p2.30_dev_ifmgr/framework/il/common/lib/vif/utest/SConscript#1 $
#

import os

Import('*')

e = env.Clone()

utest_sources = [
    'TestAsyncMessageInterface.cpp',
    'TestCodgramSocketHandler.cpp',
#    'TestDatagramSocketAcceptor.cpp',
    'TestDatagramSocketHandler.cpp',
    'TestStreamSocketHandler.cpp',
    ]

e['LIBS'] += [ 'l4l7app' ]

e['CPPPATH'] += [ '.',
                  '..',
                  '#content/traffic/l4l7/il',
                  '#framework/il/common/lib',
                  ]

testname = 'l4l7app_utest'
target = os.path.join(conf['utest_blddir'], testname)
utest = utils.runUnitTest(e, target, utest_sources)

Return('utest')

# Local Variables:
# mode:python
# End:
# vim:syntax=python
