#ifndef __ENCTIPCOMMON_H__
#define __ENCTIPCOMMON_H__




#define BEGIN_DECL_ENC_TIP_NAMESPACE namespace voip { namespace voipmedia { namespace tip {
#define END_DECL_ENC_TIP_NAMESPACE }}}
#define USING_ENC_TIP_NAMESPACE using namespace voip::voipmedia::tip
#define TIP_NS voip::voipmedia::tip


BEGIN_DECL_ENC_TIP_NAMESPACE

typedef enum TIPMediaType {
    TIPMediaAudio=0,
    TIPMediaVideo,
    TIPMediaEnd
};


typedef enum TIPNegoStatus {
    TIP_STATUS_IDLE=0,
    TIP_STATUS_EARLY,
    TIP_STATUS_FAILED,
    TIP_STATUS_MISMATCH,
    TIP_STATUS_INCOMPATIBLE,
    TIP_STATUS_LASTACKRCVD,
    TIP_STATUS_LASTACKXMIT,
    TIP_STATUS_UPDATE,
    TIP_STATUS_SECURITY_UPDATE,
    TIP_STATUS_LOCAL_PRESENTATION_START,
    TIP_STATUS_LOCAL_PRESENTATION_STOP,
    TIP_STATUS_LOCAL_PRESENTATION_FAILED,
    TIP_STATUS_REMOTE_PRESENTATION_START,
    TIP_STATUS_REMOTE_PRESENTATION_STOP,
    TIP_STATUS_REMOTE_PRESENTATION_FAILED,
    TIP_STATUS_END
};
END_DECL_ENC_TIP_NAMESPACE


#endif
