#
#  Copyright (c) 2007 by Spirent Communications Inc.
#  All Rights Reserved.
#
#  This software is confidential and proprietary to Spirent Communications Inc.
#  No part of this software may be reproduced, transmitted, disclosed or used
#  in violation of the Software License Agreement without the expressed
#  written consent of Spirent Communications Inc.
#
# $Id: //TestCenter/p2.30_dev_ifmgr/content/traffic/l2l3/il/Generator/Learning/SConscript#1 $
#

import os

Import('*')

sources = [
    'main.cpp',
    'BandwidthLoadManager.cpp',
    'CodgramSocketHandler.cpp',
    'DatagramSocketHandler.cpp',
    'StreamSocketHandler.cpp',
    ]

e = env.Clone()

e['CPPPATH'] += [ '.',
                  '#content/traffic/l4l7/il',
                  '#framework/il/common/lib', 
                  conf['tinyxml_srcdir'],
                  conf['tinyxpath_srcdir'],
                  ]

e['LIBS'] += [ 'ACE',
               'mps',
               'vif',
               'hal++',
               'sysmgr',
               'ildaemon',
               'phxlog', 
               'phxexception', 
               'phxerrno',
               ]

libname = 'l4l7app'

lib = e.SharedLibrary(target=conf['lib_dir']+'/'+libname, source=sources)
utils.installSharedLib(e, lib)

if env['utest'] :
    utest = SConscript(os.path.join('utest', 'SConscript'))
    utils.coverageReport(e, utest)

# Local Variables:
# mode:python
# End:
# vim: syntax=python
