#
#  Copyright (c) 2011 by Spirent Communications Inc.
#  All Rights Reserved.
#
#  This software is confidential and proprietary to Spirent Communications Inc.
#  No part of this software may be reproduced, transmitted, disclosed or used
#  in violation of the Software License Agreement without the expressed
#  written consent of Spirent Communications Inc.
#
# $Id: //TestCenter/p2.30_dev_ifmgr/content/traffic/l2l3/il/Generator/Learning/SConscript#1 $
#
# ----------------- README --------------------
# This only copies the new Native Protocol Emulation (NPE)  startup scripts to the proper module directory, you must build dpgd and load
# and load it to the appropriate module directory for NPE protocols to work.

import os

Import('*')

e = env.Clone()

# Install startup scripts
script_list = ['cifs.sh' ]

for script in script_list :
    target = os.path.join(conf['script_startup_blddir'], 'stc', script)
    src = script
    utils.install(e, e.Command(target, src, 'cp -f $SOURCE $TARGET'))

# Local Variables:
# mode:python
# End:
# vim: syntax=python
